name: mocki
port: 3000
endpoints:
  - path: /
    method: get
    responses:
      - statusCode: 200
        body:
          list: 
            - path: https://raw.githubusercontent.com/ploutarchosm/languages/main/list.json
